### ISSUE TITLE
Update jsonapi-resources 0.9.12

### ISSUE THREAD

**Issue by danieldocki** [tiagopog/jsonapi-utils#109]
@tiagopog can update the dependency? jsonapi-resources ~> 0.9.12

solves the error in Rails 6.1
``` 
uninitialized constant ActionController::ForceSSL
```

https://github.com/cerebris/jsonapi-resources/blob/v0.9.12/lib/jsonapi/resource_controller_metal.rb#L8

**Comment by gianniderosa** [comment]
Having the same issue on my end

**Comment by asadakbarml** [comment]
@tiagopog Will you be updating this gem? It would be really helpful to know as we want to use it...

**Comment by tiagopog** [comment]
@danieldocki It's updated in the master branch. I will first make sure that everything is working smoothly then I will release a new version of the gem.

**Comment by danieldocki** [comment]
Thanks for the great job, but I caught this error.

```
Internal Server Error: uninitialized constant JSONAPI::OperationResults Internal Server Error: uninitialized constant JSONAPI::OperationResults /Users/danieldocki/.gem/bundler/gems/jsonapi-utils-1c139822a10e/lib/jsonapi/utils/response/formatters.rb:103:in `build_response_document'
/Users/danieldocki/.gem/bundler/gems/jsonapi-utils-1c139822a10e/lib/jsonapi/utils/response/formatters.rb:39:in `jsonapi_format'
/Users/danieldocki/.gem/bundler/gems/jsonapi-utils-1c139822a10e/lib/jsonapi/utils/response/renders.rb:34:in `jsonapi_render'
```

I don't know if anyone else caught this error, but over the weekend I can look deeper into this error.

**Comment by danielgomezrico** [comment]
This is pretty important to keep the library updated and allow everyone using it to update rails, how can we update this?

Also the main library now is at `0.10.2` with a lot of fixes :(

**Comment by hennii** [comment]
Yep this library is broken currently -- PRs for upgrading support to the jsonapi-resources past 0.9.11 have not addressed the fact that 0.9.12 refactored away a class [which is being called from current version](https://github.com/tiagopog/jsonapi-utils/blob/1c139822a10e8203b9f67fa3b06cbb1eafb50529/lib/jsonapi/utils/response/formatters.rb#L103) (`JSONAPI::OperationResults)`

**Comment by JohnnyHandy** [comment]
Any news on this? I am having trouble using jsonapi-resources at version 0.10 and jsonapi-utils 0.4.2 because it is the only version that bundle allows to install

**Comment by idanab-simplee** [comment]
it seems that this gem is no longer maintained. anyone here had the chance to refactor the code to use another solution? For example, to use [jsonapi-serializer](https://github.com/jsonapi-serializer/jsonapi-serializer) ?

**Comment by danielgomezrico** [comment]
It is already updated, but it is not released on gem repository, check: 
- https://github.com/tiagopog/jsonapi-utils/issues/114
